app/models.py
from datetime import datetime
from . import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(225), unique=True, nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=False, index=True)
    password = db.Column(db.String(80), nullable=False)
    bio=db.Column(db.String(255))
    profile_pic_path=db.Column(db.String())
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    comments = db.relationship('Comment', backref='author', lazy='dynamic')
    likes = db.relationship('Like', backref='author', lazy='dynamic')
    dislikes = db.relationship('Dislike', backref='author', lazy='dynamic')
    pass_secure = db.Column(db.String(255))

   
    @property
    def password(self):
        raise AttributeError('You password attribute isnt read able')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):
        return f'User {self.username}'


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    posted_date = db.Column(db.DateTime, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    category = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref='post', lazy='dynamic')
    likes = db.relationship('Like', backref='post', lazy='dynamic')
    dislikes = db.relationship('Dislike', backref='post', lazy='dynamic')

    def save_post(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f"Post('{self.title}', '{self.posted_date}', '{self.category}')"


class Comment(db.Model):
    __tablename__="comments"
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.Text, nullable=False)
    posted_date = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comment(cls, id):
        comments = Comment.query.filter_by(post_id=id).all()
        return comments

    def __repr__(self):
        return f"Comment('{self.comment}', '{self.posted_date}')"

class Like(db.Model):
    __tablename__="likes"
    id = db.Column(db.Integer, primary_key=True)
    posted_date = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))

    def save_like(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_like(cls, id):
        likes = Like.query.filter_by(post_id=id).all()
        return likes

    def __repr__(self):
        return f'{self.posted_date}'

class Dislike(db.Model):
    __tablename__="dislikes"
    id = db.Column(db.Integer, primary_key=True)
    posted_date = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))

    def save_dislike(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_dislike(cls, id):
        dislikes = Dislike.query.filter_by(post_id=id).all()
        return dislikes

    def __repr__(self):
        return f'{self.posted_date}'
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField,StringField,PasswordField,BooleanField,SelectField,TextAreaField

from wtforms.validators import input_required,Email,EqualTo
from ..models import User
from wtforms import ValidationError

choices=['pickup','interview','product','promotion']

class PitchForm(FlaskForm):
    title=StringField("Pitch Title",validators=[input_required(message='Title required')],render_kw={"placeholder":"Pitch Title"})
    category=SelectField("Pitch Category",choices=choices,validate_choice=True)
    content=StringField("Pitch body",validators=[input_required(message='body required')],render_kw={"placeholder":"Pitch body"})
    submit=SubmitField("POST PITCH")

class CommentForm(FlaskForm):


     comment=StringField("Pitch comment",validators=[input_required(message='body required')],render_kw={"placeholder":"Pitch comment"}) 
     submit=SubmitField("Comment")

app/__init__.py
from flask import Flask   
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail

#........
mail = Mail()

def create_app(config_name):
    app = Flask(__name__)
    #........
    mail.init_app(app)
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy() 

def create_app(config_name):   
    # initializing application  
    app = Flask(__name__)
    # setting up configuration    
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions  
    bootstrap.init_app(app)  
    db.init_app(app)     
    login_manager.init_app(app)
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    # Setting config

    return app

app/main/__init__.py
from flask import Blueprint
main=Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for
from . import main
from flask_login import login_required,current_user
from ..models import User,Post,Like,Dislike,Comment
from .forms import PitchForm,CommentForm


# views
@main.route("/")
def index():
    post=Post.query.all()
    pickup=Post.query.filter_by(category='pickup').all()
    interview=Post.query.filter_by(category='interview').all()
    product=Post.query.filter_by(category='product').all()
    promotion=Post.query.filter_by(category='promotion').all()

    '''View root page function that returns the index page and its data'''
    return render_template('index.html',posts=post,pickup=pickup,interview=interview,product=product,promotion=promotion)


@main.route("/pitch",methods=['GET','POST'])
@login_required
def pitch():
    pitch=PitchForm()
    if pitch.validate_on_submit():
        title=pitch.title.data
        category=pitch.category.data
        body=pitch.content.data
        new_post=Post(title=title,category=category,content=body)
        Post.save_post(new_post)
        return redirect(url_for('.index'))
    return render_template("pitch.html",pitch_form=pitch)
    
@main.route('/upvote/<id>', methods=['GET', 'POST'])
@login_required
def like(id):
    data = Like.get_like(id)
    output = f'{current_user.id}:{id}'
    for vote in data:
        res = f'{vote}'
        if output == res:
            return redirect(url_for('main.index', id=id))
        else:
            continue
    new_upvote = Like(post_id=id)
    new_upvote.save_like()
    return redirect(url_for('main.index', id=id))

@main.route('/downvote/<id>', methods=['GET', 'POST'])
@login_required
def dislike(id):   
    data = Dislike.get_dislike(id)
    output = f'{current_user.id}:{id}'
    for vote in data:
        res = f'{vote}'
        if output == res:
            return redirect(url_for('main.index', id=id))
        else:
            continue
    new_downvote = Dislike(post_id=id)
    new_downvote.save_dislike()
    return redirect(url_for('main.index', id=id))
    
@main.route('/comment/<id>', methods=['GET', 'POST'])
@login_required
def comment(id):
    comment_form = CommentForm()
    post = Post.query.get(id)
    fetch_all_comments = Comment.query.filter_by(post_id=id).all()
    if comment_form.validate_on_submit():
        comment = comment_form.comment.data
        p_id = id
        user_id = current_user._get_current_object().id
        new_comment = Comment(comment=comment, user_id=user_id, post_id=p_id)
        new_comment.save_comment()
        return redirect(url_for('.comment', id=p_id))
    return render_template('comment.html', comment_form=comment_form, post=post, all_comments=fetch_all_comments)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
 <title>Pitch</title>
{%block styles%} 
{{super()}}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}" />
{%endblock%} 

{% block navbar %} {% include 'navbar.html' %} {% endblock %}

app/templates/comment.html
{% extends 'base.html'%} {% import 'bootstrap/wtf.html' as wtf %} {% block
    content %}
    <div class="container comments">
      <div class="row">
        {% if all_comments %}
        <div class="col-md-7">
          <h3 class="text"><u>All comments for the post</u></h3>
          {% for comment in all_comments %}
          <div class="card w-90 mb-3">
            <div class="card-body">
                <h5>{{comment.title}}</h5>
                <p class="card-title">{{ comment.comment }}</p>
              </div>
            </div>
            {% endfor %}
          </div>
          <div class="col-md-5 commentform">{{wtf.quick_form(comment_form)}}</div>
        </div>
        {%else%}   
        <div class="card w-90 mb-3">
            <div class="card-body">
              <p class="card-title">No Available Comments</p>
            </div>
          </div>
          <div class="col-md-5">{{wtf.quick_form(comment_form)}}</div>
          {%endif%}
        </div>
        
        {% endblock%}         

app/templates/dislike.html
{%extends 'base.html'%} {% import 'bootstrap/wtf.html' as wtf%} 
{%block content%}
    
    <div class="container">
    <h2 class="text-center">Dislike</h2>
    {{wtf.quick_form(dislike_form)}}
    <p>
    </p>
    </div>
    {%endblock%} 

app/templates/index.html
{%extends 'base.html'%}
{% import 'macro.html' as macro%}
<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
<!-- Content block -->
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 ">
            <h2>Pickup Lines</h2>
        {{ macro.alldisplays(pickup)}}

        </div>
        <div class="col-md-3">
            <h2>Interview</h2>
        {{ macro.alldisplays(interview)}}
        </div>
        <div class="col-md-3">
            <h2>Product</h2>
        {{ macro.alldisplays(product)}}

        </div>
        <div class="col-md-3">
        <h2>Promotion</h2>

        {{ macro.alldisplays(promotion)}}
       
        </div>
    </div>
{% endblock%}

app/templates/like.html
{%extends 'base.html'%} {% import 'bootstrap/wtf.html' as wtf%} 
{%block content%}
    
    <div class="container">
    <h2 class="text-center">Like</h2>
    {{wtf.quick_form(like_form)}}
    <p>
    </p>
    </div>
    {%endblock%} 

app/templates/macro.html
{%macro alldisplays(alldatas)%}
<div class="container-fluid">
    {%for data in alldatas%}
    {{data.title}}<br>  
    {{data.category}}<br>   
    {{data.content}}
    <hr>
    <button class="btn btn-info">
        <a href="{{url_for('main.like',id = data.id)}}">
          <i class="fa fa-thumbs-up"></i> Upvote {{data.likes.count()}}</a>
      </button>
      <button class="btn btn-info">
        <a href="{{url_for('main.dislike',id = data.id)}}">
          <i class="fa fa-thumbs-down"></i> Downvote {{data.dislikes.count()}}</a>
      </button>
      <button class="btn btn-info">
        <a href="{{url_for('main.comment',id = data.id)}}"> Comment</a>
      </button>
    
    {%endfor%}
</div>

{%endmacro%}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgba(0, 0, 0, 0.2);">
    <div class="container-fluid">
      <a class="navbar-brand" href="#" style="font-size: 20px;">One Minute Pitch</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto mt-4 mt-lg-0">
          <li class="nav-item px-5">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item px-5">
            <li><a href="{{url_for('main.pitch')}}" px-5>New Pitch</a></li>
          </li>
          {%else%}
          <li class="nav-item px-5">
            <li><a href="">Profile</a></li>
          </li>
          <li class="nav-item px-5">
            <li><a href="{{url_for('auth.register')}}" px-5>Sign Up </a></li>
          </li>
          <li class="nav-item px-5">
            <li><a href="{{url_for('auth.login')}}" px-5>Sign In</a></li>
          </li>
        </ul>
        {% endif %}
      </div>
    </div>
  </nav>

app/templates/pitch.html
{%extends 'base.html'%} {% import 'bootstrap/wtf.html' as wtf%} 
{%block content%}
    <div class="container">
    <h2 class="text-center">PITCH FORM</h2>
    {{wtf.quick_form(pitch_form)}}
    <p>
    </p>
    </div>
    {%endblock%} 